### ISSUE TITLE
Can you use tags or branches to mark versions?

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/STM32CubeF0#1]
WIthout tags, it's hard to track changes between releases.

Thank you.
 - pa

**Comment by CCASTM** [comment]
Hello Pavel,
This is a mistake in our recent publications. Will be corrected today
Regards
Christophe

**Comment by ASELSTM** [comment]
Dear Pavel,

Thank you for your contribution. Indeed, a mistake occurred during publication. The tag is now available in the STM32CubeF0 package, the issue is therefore fixed and will be closed.

With regards,
Eya
