### ISSUE TITLE
Conflicting types for 'assert_failed'

### ISSUE THREAD

**Issue by david-oz00** [STMicroelectronics/STM32CubeF0#3]
**Describe the set-up**
Hardware: Proprietary hardware containing STM32F030RCTx.
IDE: VisualGDB with GCC 9.2.1

**Describe the bug**
When **USE_FULL_ASSERT** is enabled, STM32CubeMX generates this function in _main.c_:

`void assert_failed(char *file, uint32_t line)`

however the prototype in _stm32f0xx_hal_conf.h_ has been changed to this:

`void assert_failed(uint8_t* file, uint32_t line);`

This causes a compile error from GCC **"error: conflicting types for 'assert_failed'"**

**How To Reproduce**
1. Indicate the global behavior of your application project
The application uses STM32CubeMX built in assert mechanism.  This defect occurs at compile time.

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)
 _stm32f0xx_hal_conf.h_ (which is generated from the _stm32f0xx_hal_conf_template.h_) has been updated with a new prototype, but the function body in _main.c_ has not been updated.

3. The use case that generates the problem
Compiling the application.

4. How we can reproduce the problem

- Create a project in STM32CubeMX using this mcu package.  Ensure Enable Full Assert is ticked (Project Manager\Code Generator\Hal Settings).
- Generate the code and compile the project.  A compile error is generated as in the description above.

**Additional context**
It looks like someone updated the prototype but forgot to update the body. The funny thing is _**uint8_t***_ is not correct anyway. I think it should be changed to _**const char***_, or at least keep it at _**char***_

**Screenshots**
None

**Comment by ALABSTM** [comment]
Hi David,

As said in a previous [comment](https://github.com/STMicroelectronics/STM32CubeH7/issues/23#issuecomment-582294946), aspects related to Cube MX tool are not handled at GitHub level. They are rather treated at **ST Community** level, precisely within the [Cube MX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated section.

Please, allow me to close this issue. Thank you for your comprehension.

With regards,
