### ISSUE TITLE
stm32F042x6 CAN defs : wrong number of filter banks ?

### ISSUE THREAD

**Issue by fenugrec** [STMicroelectronics/STM32CubeF0#9]
Hi,
looking at
https://github.com/STMicroelectronics/STM32CubeF0/blob/4390ff6bfb693104cf97192f98c3dc9e3a7c296a/Drivers/CMSIS/Device/ST/STM32F0xx/Include/stm32f042x6.h#L1580

it seems the bxCAN FM1R register has bits defined up to FBM27, but the ref manual RM0091 only lists FBM0..FBM13 . Seems to be the same situation for other filter registers (FS1R, FFA1R..)

Is there a reason for this apparent doubling of bit defines ?

Incidentally, in RM0091 (rev. 9) Table 118 "bxCan register map and reset values" also incorrectly lists 28 filter banks. Probably copypasted from some other RM ?

**Comment by RKOUSTM** [comment]
Hi @fenugrec ,

The issue you pointed out has been confirmed, an update on the RM0091 (rev. 9) will be made available in future release. Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 101205

**Comment by RKOUSTM** [comment]
Hi @fenugrec,

The fix you requested has been implemented and is now available in the frame of the latest STM32CubeF0 package V1.11.3 release. 

This issue can be closed now. Thank you again for your contribution.

With regards,
